.PHONY: check test race fmt vet lint coverage examples security

check:
	git diff --check
	go test -count=1 ./...
	go test -race -count=1 ./...
	go vet ./...
	golangci-lint run ./...
	go test -coverprofile=coverage.out ./...
	go test -run '^Example' ./...
	govulncheck ./...

test:
	go test -count=1 ./...

race:
	go test -race -count=1 ./...

fmt:
	gofmt -w .

vet:
	go vet ./...

lint:
	golangci-lint run ./...

coverage:
	go test -coverprofile=coverage.out ./...

examples:
	go test -run '^Example' ./...

security:
	govulncheck ./...
